### ISSUE TITLE
Unexpected token: name (PopOverComponent)  while compiling

### ISSUE THREAD

**Issue by anagh416** [meiriko/ng2-pop-over#2]
ERROR in main.1936f825efd61c36f980.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (PopOverComponent) [main.1936f825efd61c36f980.bundle.js:23655,4]
Child html-webpack-plugin for "index.html":
        + 4 hidden modules

above error is coming while running below command 
npm run build:prod.
if u need any code for config file  let me know plz

**Comment by anagh416** [comment]
tsconfig.json

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "baseUrl": "./src",
    "paths": {
    },
    "lib": [
      "dom",
      "es6"
    ]
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

**Comment by meiriko** [comment]
The current config is es6, did you try to change it to es5 when you got this result or did you try to use the library in an es5 project?

**Comment by meiriko** [comment]
Thx @anagh416 , it is fixed in 10c08cbf88396d2990378974a87af00914facafe, please update to version 0.9.33 and see if it fixed the issue.

**Comment by anagh416** [comment]
@meiriko  it seems to be working now no issue in compilation. i still need to test in our Integration Environment so i 'll let you know if i encounter any issue. thanks for your help .
