### ISSUE TITLE
PopoverModule is not an NgModule

### ISSUE THREAD

**Issue by SixStringSkeptic** [meiriko/ng2-pop-over#3]
Hello, I'm getting an error today when trying to run my app with ng serve (used angular-cli to create project) that says:

10% building modules 2/2 modules 0 activeError: PopoverModule is not an NgModule
at AotPlugin.getNgModuleMetadata (C:\Dev\ecam\ecam\node_modules\@ngtools\webpack\src\plugin.js:332:19)
    at C:\Dev\ecam\ecam\node_modules\@ngtools\webpack\src\plugin.js:345:51
    at Array.map (native)
    at AotPlugin.extractLoadChildren (C:\Dev\ecam\ecam\node_modules\@ngtools\webpack\src\plugin.js:343:14)
    at AotPlugin._processNgModule (C:\Dev\ecam\ecam\node_modules\@ngtools\webpack\src\plugin.js:272:38)
    at C:\Dev\ecam\ecam\node_modules\@ngtools\webpack\src\plugin.js:242:39
    at tryCatch (C:\Dev\ecam\ecam\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (C:\Dev\ecam\ecam\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (C:\Dev\ecam\ecam\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (C:\Dev\ecam\ecam\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Do you have any suggestions on how to fix this error?

**Comment by meiriko** [comment]
Are you using AoT? What cmd line options to you pass to ng serve?
I suspect that my module is not AoT "compliant".

**Comment by SixStringSkeptic** [comment]
Sorry, not sure what you mean by AoT? It was working yesterday, I was
getting the popovers and everything. I don't understand what this could be
caused by.

**Comment by SixStringSkeptic** [comment]
Ah, I see now AoT, I think ng serve command does that.

**Comment by meiriko** [comment]
Did you update your angular cli?

Can you please specify how you run ng serve? What parameters do you pass? is it 'ng serve' or 'ng serve param1 --flag1' ?

**Comment by SixStringSkeptic** [comment]
I haven't updated angular cli in the last week, just started using it last
week, and I just use "ng serve" with no parameters.

**Comment by meiriko** [comment]
strange. Is you project under git? Can you see what changed in other files that might have broken the build/serve?

Also, try to do 'ng bulid' and 'ng build --prod', see if they work or fail as well.

**Comment by SixStringSkeptic** [comment]
I haven't added it to git yet, unfortunately - I asked my supervisor for a
repo, and he hasn't set it up yet.  Thanks for the suggestions, I've had to
comment it out for now, and will come back to it later, since this
prototype is due soon.  Thanks for your help.

**Comment by meiriko** [comment]
okay. If you do find the problem please update.

Btw, you do not need a remote repo, you can always start a local copy simply by doing 'git init'. From that point on you can manage local version so you can always see the history of your changes. Once you get a  remote repo, you can add it to your remotes and push to it.

**Comment by SixStringSkeptic** [comment]
Yeah, thanks for the tip.  This is/was a prototype that I never really
intended to get as big as quick as it did, but live and learn.  I know
better, I promise :)

**Comment by meiriko** [comment]
Is it working now? Can I close this?

**Comment by SixStringSkeptic** [comment]
I coded my own, so you can close.
