### ISSUE TITLE
PopoverModule is not an NgModule

### ISSUE THREAD

**Issue by NivedhithaV** [meiriko/ng2-pop-over#6]
From angular-cli team

> It basically means that the modules you are depending on are not in the right shape to be used in Angular 2 apps built with the cli. It's up to the package maintainer to fix this.

**Comment by meiriko** [comment]
Will look into it. Can you provide more details:
1. What angular cli version are you using?
2. What is the full error message?

**Comment by meiriko** [comment]
Should be fixed in e1b5ad4. Please confirm and I will close the issue.

**Comment by NivedhithaV** [comment]
Thank you! It works. Thanks for your quick response,
