### ISSUE TITLE
Hide(), when click on Popover??

### ISSUE THREAD

**Issue by wahiebi** [meiriko/ng2-pop-over#7]
is there a way to hide the popover when clicking on it directly ?

**Comment by meiriko** [comment]
There should be. Either by generating a click observable and using the 'hide-on' property or:

<pop-over #myPopOver>
   <div (click)="myPopOver.hide()">content goes here</div>
</pop-over>

look at the documentation/demo for '.hide()'

Please confirm it works so I can close the issue (or close it yourself).

**Comment by wahiebi** [comment]
I used it and the message is hiding  just when i click on the component where i call the pop-over, or by mouseleave
and i would know if there is a way when i click on the (pop-over)message it will hide 
(anyway thx for the fast answer)
